export const AllProjects = [
  {
    id: 1,
    name: "MyProducts",
    url: "https://myproducts1.netlify.app/",
    tag: ["React", "Node", "postgre"],
    image: "https://i.postimg.cc/hjt6mXt3/my-Products.png",
  },
  {
    id: 2,
    name: "WaiterAPP",
    url: "https://github.com/CarmoDev/WaiterAPP",
    tag: ["React", "TypeScript", "Node", "mongo", "React-Native"],
    image: "https://i.postimg.cc/vmQNR4fH/waiterapp.png",
  },
  {
    id: 3,
    name: "API URL to QrCode",
    url: "https://github.com/CarmoDev/Url_To_QrCode",
    tag: ["Node"],
    image: "https://i.postimg.cc/ryb3dFXQ/code.png",
  },
  {
    id: 4,
    name: "Animais Fantásticos",
    url: "https://carmodev.github.io/Animais-Fantasticos_origamid/",
    tag: ["HTML", "CSS"],
    image: "https://i.postimg.cc/mrwKhYBH/animais-Fantasticos.png",
  },
  {
    id: 5,
    name: "Extrair link",
    url: "https://github.com/CarmoDev/Validar-Links",
    tag: ["Node"],
    image: "https://i.postimg.cc/ryb3dFXQ/code.png",
  },
  {
    id: 6,
    name: "Carousel",
    url: "https://carmodev.github.io/Slides/",
    tag: ["HTML", "CSS"],
    image: "https://i.postimg.cc/9F7Sy5cV/carousel.png",
  },
  {
    id: 7,
    name: "GeekFlix",
    url: "https://carmodev.github.io/GeekFlix/",
    tag: ["HTML", "CSS"],
    image: "https://i.postimg.cc/FHbBnyfB/GeekFlix.png",
  },
  {
    id: 8,
    name: "WeatherAPP",
    url: "https://carmodev.github.io/Projeto_1-Clima/",
    tag: ["HTML", "CSS"],
    image: "https://i.postimg.cc/85cX5xZ2/weather.png",
  },
  {
    id: 9,
    name: "Purple Snake",
    url: "https://carmodev.github.io/Projeto_1-Clima/",
    tag: ["React", "TypeScript", "CSS"],
    image: "https://i.postimg.cc/cLGzm9J3/purplesnake.png",
  },
  {
    id: 10,
    name: "Carmo Music",
    url: "https://carmomusic.netlify.app/",
    tag: ["React"],
    image: "https://i.postimg.cc/SRXPZH86/music.png",
  },
  {
    id: 11,
    name: "grade calculator",
    url: "https://carmodev.github.io/Calculadora-de-media/",
    tag: ["HTML", "CSS"],
    image: "https://i.postimg.cc/XqTztxcT/media.png",
  },
  {
    id: 12,
    name: "product card",
    url: "https://productmargotsofa.netlify.app/",
    tag: ["React"],
    image: "https://i.postimg.cc/50KGSfH9/product.png",
  },
];
